// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCommand(arg1:Array<main.VerbConfig>,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string,arg7:string,arg8:string,arg9:string):Promise<string>;

export function LoadConfig(arg1:string):Promise<main.Config>;

export function LoadLastState():Promise<main.Config>;

export function ParseCommand(arg1:string):Promise<main.Config>;

export function Preview(arg1:string,arg2:Array<main.VerbConfig>,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:string,arg8:string):Promise<string>;

export function ReadFileHead(arg1:string,arg2:number):Promise<string>;

export function SaveConfig(arg1:main.Config,arg2:string):Promise<void>;

export function SaveLastState(arg1:main.Config):Promise<void>;

export function SaveOutput(arg1:string):Promise<void>;

export function SelectInputFile():Promise<string>;
