// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommand(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['GetCommand'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function LoadLastState() {
  return window['go']['main']['App']['LoadLastState']();
}

export function ParseCommand(arg1) {
  return window['go']['main']['App']['ParseCommand'](arg1);
}

export function Preview(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['Preview'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PreviewFile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ReadFileHead(arg1, arg2) {
  return window['go']['main']['App']['ReadFileHead'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveLastState(arg1) {
  return window['go']['main']['App']['SaveLastState'](arg1);
}

export function SaveOutput(arg1) {
  return window['go']['main']['App']['SaveOutput'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}
